# production stage
FROM nginx:stable-alpine as production-stage
RUN apk update --no-cache
COPY ./dist/pwa/  /usr/share/nginx/html
# handle reload in router history mode
RUN sed -i '/location\ \//a \\t \ try_files \$uri \$uri/ /index.html; \' /etc/nginx/conf.d/default.conf
EXPOSE 80

ENTRYPOINT nginx -g 'daemon off;'
