version: '3.9'

services:
  pizzarree_db:
    image: postgres
    container_name: pizzarree_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=pizzarree_db
      - POSTGRES_USER=pizzarree
      - POSTGRES_PASSWORD=pizzarree_pass
      - POSTGRES_DB=pizzarree_db
      - DATABASE_PORT=5432
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    restart: unless-stopped


  backend:
    container_name: backend
    # build:
      # context: ./pizzarree_api
      # dockerfile: ./pizzarree_api/Dockerfile
    image: registry.secure-relay.online/pizzarree_api:latest
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    volumes:
      # - ./pizzarree_api:/code/app # dev
      - ./docker_data/media/:/code/app/media/
      # - ./docker_data/db.sqlite3:/code/app/db.sqlite3
#    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_FRONTEND_URL=localhost
      - DJANGO_ALLOWED_HOSTS=localhost,pizzarree.net,elife.mac
      - DJANGO_DEBUG=1
      - DJANGO_DOMAIN = localhost
      - DATABASE_USER=pizzarree
      - DATABASE_PASSWORD=pizzarree_pass
      - DATABASE_DB=pizzarree_db
      - POSTGRES_HOST=pizzarree_db
      - DJANGO_CORS_ALLOWED_ORIGINS=https://elife.mac:8080,https://localhost:8080,http://localhost:8080
      - DJANGO_EMAIL_HOST=smtp.mailtrap.io
      - DJANGO_EMAIL_PROT=2525
      - DJANGO_EMAIL_HOST_USER=a571812ba39b6d
      - DJANGO_EMAIL_HOST_PASSWORD=ee0e4489a103b8
      - DJANGO_STRIPE_API_KEY=pk_test_RUZqAN8CkTK39VGr7FuIxPWE
      - DJANGO_STRIPE_API_SECRET=sk_test_CHbkFTgQWREZlA5ff17sCy1Q
    command: "uwsgi --https 0.0.0.0:8000,cert/server.crt,cert/server.key --wsgi-file pizzarree_api/wsgi.py --master --processes 4 --threads 2 --static-map /static=/code/app/static --static-map /media=/code/app/media --python-auto-reload=1"
    # command: "uwsgi --http 0.0.0.0:8000 --wsgi-file pizzarree_api/wsgi.py --master --processes 4 --threads 2 --static-map /static=/code/app/static --static-map /media=/code/app/media --python-auto-reload=1"
    depends_on:
      - pizzarree_db


  frontend:
    container_name: frontend
    # build:
    #   context: ./pizzarree
    image: registry.secure-relay.online/pizzarree_temp:latest
    
#      dockerfile: ./pizzarree/Dockerfile
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    env_file:
      - ./pizzarree/.env
    # volumes:
    #   - ./pizzarree:/app
    # command: "quasar dev -p 80"
    # command: "quasar serve dist/pwa --https --cert cert/server.crt --key cert/server.key -p 80"
    depends_on:
      - backend


volumes:
  postgres-data:
 

