# Generated by Django 4.2.7 on 2023-11-29 02:59

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('type', models.CharField(choices=[('SALE', 'Sale'), ('SERVICE', 'Service')], default=('SALE', 'Sale'), max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('published', models.BooleanField(db_index=True, default=False)),
                ('featured', models.BooleanField(default=False)),
                ('info', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='uploads/products/', verbose_name='cover_image')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-created',),
                'unique_together': {('name', 'slug', 'id')},
            },
        ),
    ]
